fail_fast: true
repos:
  - repo: local
    hooks:
    - id: ruff formatter
      name: ruff formatter
      entry: uv run ruff format
      language: system
      types: [python]
    - id: ruff linter
      name: ruff linter
      entry: uv run ruff check
      language: system
      types: [python]
    - id: mypy type checker
      name: mypy type checker
      entry: uv run mypy
      language: system
      types: [python]
