[project]
name = "backend-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "pre-commit>=4.1.0",
    "ruff>=0.9.9",
]
